### PR TITLE
support spotify headless oauth

### PR DESCRIPTION
**Pull request by ahxxm**

### CODE REVIEW

**Comment by sigma67** [comment]
Honestly I'd prefer to detect this situation and act accordingly instead of introducing some environment variable.

What issues are you having in WSL? If they are valid, can't we just detect WSL?

**Comment by ahxxm** [comment]
sorry I forgot to update the description, it could be WSL(detectable through environment variables I think? not familiar with what Microsoft guarantees) or another headless environment like a server(I've no clue how to detect)

for now, the library `spotipy` doesn't open a browser, it silently skips this step and directly asks for the redirect URL as if I've authorized with that tab

after the change the library will give me a link for authorization

**Comment by sigma67** [comment]
How about `sys.stdin.isatty()`? Does that detect your environment?

**Comment by ahxxm** [comment]
it returns `True` on my VPS, does it return `False` for you or when the library can open a new browser tab?

**Pull request closed without merging**
